PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
prefix geo: <http://www.opengis.net/ont/geosparql#>
prefix admissie: <https://iisg.amsterdam/Admissieregisters_geocoded/vocab/>
prefix hsnvocab: <https://iisg.amsterdam/hsn2013a/vocab/>
prefix hsn: <https://iisg.amsterdam/hsn2013a/>

SELECT ?ID ?sex ?origin ?year ?month ?occman ?occwife ?hisclass ?hisconr ?distance  WHERE {
  ?sub admissie:ID ?ID .
  ?sub admissie:Origin ?origin .
  ?sub admissie:dist_to_haarlem_rounded ?distance . 
  ?sub admissie:man_or_woman ?sex .
  ?sub admissie:Year ?year .
  ?sub admissie:Month ?month .
 
OPTIONAL {?sub admissie:Occupation_man ?occman }  # get both male and female occupations .
OPTIONAL {?sub admissie:Occupation_wife ?occwife } .
 ?sub hsnvocab:occupationalTitle ?occ2 .
 ?occ2 hsn:hisclass ?hisclass .
 ?hisco skos:member ?occ2 .
 ?hisco skos:inScheme ?scheme .
 ?hisco skos:notation ?hisconr .

 # add wkt:Point to display on map:
 # ?sub admissie:Origin ?origin .
 # ?origin geo:asWKT ?geoloc. 
        
        
}
