#+ summary: query occupations coded in HISCO and their characteristics 
#+ tags:
#+      - hisco

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX hisco: <http://data.socialhistory.org/resource/hisco/>
PREFIX hisco-cat: <http://data.socialhistory.org/resource/hisco/code/hisco/>

## show all community coded entries for a given hisco (and their provenance)
## limited to a specific language

SELECT DISTINCT ?code ?job ?label ?provenance
WHERE { 
  hisco:category skos:member ?code .
  ?code skos:member ?job .
  hisco-cat:54010 skos:member ?job .
  ?job skos:prefLabel ?label .
  ?job prov:wasDerivedFrom ?provenance .
  
  # if you also want 'raw' (not nicely spelled) job titles comment this out
  # OPTIONAL {hisco:job skos:hiddenLabel ?label} 
  
  # uncomment below to select Dutch titles only (or other language: e.g. change "nl" into "se" for Swedish)
  # FILTER(lang(?label) = "nl") 
} 

LIMIT 10
